apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: python-sample
  namespace: python-sample
spec:
  triggers:
    - name: python-sample-triggerbinding
      bindings:
        - ref: python-sample-triggerbinding
          kind: TriggerBinding
      template:
        ref: python-sample-triggertemplateN
