apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: python-sample-pipeline
  namespace: python-sample
spec:
  params:
    - default: 'false'
      name: WORKSPACE_BASIC_AUTH_DIRECTORY_BOUND
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/python-sample/python-sample
      name: IMAGE_NAME
      type: string
    - default: 'https://github.com/sforeman-rh/rosa-automation'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: python-sample
      name: APP_NAME
      type: string
    - default: python-sample
      name: PATH_CONTEXT
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REVISION)
        - name: SUBDIRECTORY
          value: ''
        - name: DELETE_EXISTING
          value: 'true'
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLS_VERIFY
          value: 'false'
      runAfter:
        - fetch-repository
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
      params:
        - name: SCRIPT
          value: |
            oc new-app --docker-image $(params.IMAGE_NAME)
      runAfter:
        - build
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: openshift-client
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
  workspaces:
    - name: workspace
