apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: python-sample-triggerbinding
  namespace: python-sample
spec:
  params:
    - name: gitrevision
      value: $(body.after)
    - name: gitrepositoryurl
      value: $(body.repository.html_url)
