apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: python-sample-triggertemplate
  namespace: python-sample
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: python-sample-
      spec:
        params:
          - name: WORKSPACE_BASIC_AUTH_DIRECTORY_BOUND
            value: 'true'
          - name: DEPLOYMENT_NAME
            value: python-sample
          - name: GIT_URL
            value: $(tt.params.gitrepositoryurl)
          - name: GIT_REVISION
            value: $(tt.params.gitrevision)
          - name: IMAGE
            value: >-
              image-registry.openshift-image-registry.svc:5000/python-sample/python-sample:latest
          - name: TLSVERIFY
            value: 'false'
          - name: working-dir
            value: /
        pipelineRef:
          name: python-sample-pipeline
        workspaces:
          - name: basic-auth
            secret:
              secretName: github-creds
          - name: workspace
            emptyDir: {}
